name: First workflow1
#set trigger

on:
   push:
       branches:
            - main

#create jobs
jobs: 
    print-message:
        runs-on: ubuntu-latest
        steps:
            # step1
            - name: print welcome message 
              run: echo 'welcome to gitub action'
            # step2
            - name: print hello message 
              run: echo 'hello message '
            